<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function libguides_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.libguides':
      return t('
        <h2>LibGuies integration for Drupal.</h2>
        <h3>Instructions</h3>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal installation) and enable in <strong>/admin/modules</strong>.</p>
        <p>Then, visit <strong>/admin/config/development/libguides</strong> and enter your LibGuides app client ID and client secret.</p>
        <h3>Attention</h3>
        <p>Most bugs have been ironed out, holes covered, features added. But this module is a work in progress. Please report bugs and suggestions, ok?</p>
      ');
  }
}

?>